ekf_node_odom:
    ros__parameters:
        use_sim_time: true
        frequency: 20.0
        sensor_timeout: 0.5
        two_d_mode: true
        transform_time_offset: 0.0
        transform_timeout: 0.0
        # print_diagnostics: true
        debug: false
        # debug_out_file: /path/to/debug/file.txt
        publish_tf: true
        publish_acceleration: false
        reset_on_time_jump: true

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom

        odom0: /odom
        odom0_config: [true, true, false,     # x, y, z
                       false, false, true,    # r, p, y
                       true,  false,  false,  # vx, vy, vz
                       false, false, true,    # wx, wy, wz
                       false, false, false]   # ax, ay, az
        # odom0_queue_size: 2
        # odom0_nodelay: false
        odom0_differential: false
        odom0_relative: false
        # odom0_pose_rejection_threshold: 5.0
        # odom0_twist_rejection_threshold: 1.0

        imu0: /imu
        imu0_config: [false, false, false,
                      true,  true,  true,
                      false, false, false,
                      true,  true,  true,
                      false,  false,  false]
        
        # imu0_nodelay: false
        imu0_differential: false
        imu0_relative: true
        # imu0_queue_size: 7
        # imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
        # imu0_twist_rejection_threshold: 0.8                #
        # imu0_linear_acceleration_rejection_threshold: 0.8  #
        imu0_remove_gravitational_acceleration: true
        
        twist0: /cmd_vel
        use_control: true
        # stamped_control: false
        control_timeout: 0.2
        control_config: [true, false, false, false, false, true]
        acceleration_limits: [2., 0.0, 0.0, 0.0, 0.0, 6.28]
        deceleration_limits: [2., 0.0, 0.0, 0.0, 0.0, 10.]
        #acceleration_gains: [0.8, 0.0, 0.0, 0.0, 0.0, 0.9]
        #deceleration_gains: [1.0, 0.0, 0.0, 0.0, 0.0, 1.0]